spring:
  datasource:
    url: jdbc:hsqldb:mem:library_db
    username: sa
    password:

  sql:
    init:
      mode: never

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true