CREATE TABLE IF NOT EXISTS public.genres
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
    name varchar(20) NOT NULL,
    CONSTRAINT genres_pk PRIMARY KEY (id)
);

INSERT INTO public.genres (name) VALUES('Mystery');
INSERT INTO public.genres (name) VALUES('Thriller');
INSERT INTO public.genres (name) VALUES('Horror');
INSERT INTO public.genres (name) VALUES('Historical');
INSERT INTO public.genres (name) VALUES('Western');
INSERT INTO public.genres (name) VALUES('Fantasy');