version: "2"
services:
  eureka:
    container_name: eureka
    build: ./eureka
    ports:
      - "8761:8761"
  library_services:
    build: ./library-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/library
      eureka.client.service-url.defaultZone: http://host.docker.internal:8761/eureka
    depends_on:
      - eureka
    ports:
      - "8090:8090"
  resilience:
    build: ./resilience
    environment:
      - eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka
    depends_on:
      - eureka
    ports:
      - "8080:8080"
  mongo:
    image: mongo:6.0.6
    ports:
      - "27017:27017"